#!/usr/bin/env bash

#: exec_target = cli

## Run project's Behat tests.
##
## Usage: fin behat [--profile=profile] [--path=path] [arguments]
##
## path     defaults to tests/behat
## profile  defaults to docksal

# Abort if anything fails
set -e

# Environment variables passed from fin:
#
#   $PROJECT_ROOT - (string) absolute path to NEAREST .docksal folder
#   $VIRTUAL_HOST - (string) ex. projectname.docksal
#   $DOCROOT - name of the docroot folder
#   $DOCKER_RUNNING - (string) "true" or "false"

params=''
path='tests'
profile=docker
file=behat.yml
for i in "$@"; do
	case "$i" in
	    --profile=*)
            profile="${i#*=}"
            ;;
		--path=*)
			path="${i#*=}"
			;;
		--file=*)
			file="${i#*=}"
			;;
		*)
			params="$params$i "
			;;
	esac;
done

BEHAT_PATH="${PROJECT_ROOT}/${path}"
BEHAT_YML_PATH="${BEHAT_PATH}/${file}"

if [[ ! -f "$BEHAT_YML_PATH" ]]; then
	echo "Could not find behat.yml. Creating..."
	cp $BEHAT_PATH/behat.template.yml $BEHAT_PATH/behat.yml
fi

if [[ ${VNC_PORT_MAPPING%\:5900*} > 0 ]]; then
    # Launch VNC viewer
    VNC_URL="vnc://:secret@${VIRTUAL_HOST}:${VNC_PORT_MAPPING%\:5900*}"
    echo "Open $VNC_URL"
    #open "$VNC_URL"
fi

# Launch Behat tests
cd ${PROJECT_ROOT}/${path} && ${PROJECT_ROOT}/vendor/bin/behat --tags="~@ignore" --config ${BEHAT_YML_PATH} -p ${profile} ${params}
